const lessons = [
  {
    id: "1",
    title: "01. Introduction",
    progress: 0.78,
    lectures: "3",
    duration: "7 min",
    tutorials: [
      {
        id: "1",
        name: "Setting up individual Camera Rigs",
        duration: "00:44",
        isUnlocked: true,
      },
      {
        id: "2",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "03:49",
        isUnlocked: true,
      },
      {
        id: "3",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "05:25",
        isUnlocked: false,
      },
    ],
  },
  {
    id: "2",
    title: "02. Movement in VR",
    progress: 0.25,
    lectures: "3",
    duration: "7 min",
    tutorials: [
      {
        id: "1",
        name: "Setting up individual Camera Rigs",
        duration: "00:44",
        isUnlocked: true,
      },
      {
        id: "2",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "03:49",
        isUnlocked: true,
      },
      {
        id: "3",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "05:25",
        isUnlocked: false,
      },
    ],
  },
  {
    id: "3",
    title: "03. Distance Grabber",
    progress: 0.33,
    lectures: "3",
    duration: "7 min",
    tutorials: [
      {
        id: "1",
        name: "Setting up individual Camera Rigs",
        duration: "00:44",
        isUnlocked: true,
      },
      {
        id: "2",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "03:49",
        isUnlocked: true,
      },
      {
        id: "3",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "05:25",
        isUnlocked: false,
      },
    ],
  },
  {
    id: "4",
    title: "04. Snap Zones",
    progress: 0.1,
    lectures: "3",
    duration: "7 min",
    tutorials: [
      {
        id: "1",
        name: "Setting up individual Camera Rigs",
        duration: "00:44",
        isUnlocked: true,
      },
      {
        id: "2",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "03:49",
        isUnlocked: true,
      },
      {
        id: "3",
        name: "Setting Up VRTKs Tracked Alias",
        duration: "05:25",
        isUnlocked: false,
      },
    ],
  },
];

const courses1 = [
  // {
  //   id: "1",
  //   category: "Science",
  //   class: "Class 1",
  //   url:"http://192.168.30.1/frm/ui/cat/frmpackage/646fb9bdbcafc/content/Caminandes%202%20-%20Gran%20Dillama.mp4",
  //   name: "Chapter 1 of science – Chemical Reactions and Equations.",
  //   author: "Jack Smith",
  //   thumbnail: { uri: "https://via.placeholder.com/270x270" },
  //   image: { uri: "https://via.placeholder.com/690x360" },
  //   icon: { uri: "https://via.placeholder.com/600x600" },
  //   preview_240x240: {
  //     uri: "https://via.placeholder.com/240x240",
  //   },
  //   preview_330x330: {
  //     uri: "https://via.placeholder.com/330x330",
  //   },
  //   preview_480x288: {
  //     uri: "https://via.placeholder.com/480x288",
  //   },
  //   preview_1005x495: {
  //     uri: "https://via.placeholder.com/1005x495",
  //   },
  //   location: "London Universiry",
  //   instructor: "Elizabeth Parker",
  //   instructorPhoto: { uri: "https://via.placeholder.com/273x273" },
  //   instructorRating: "4.5",
  //   instructorReviews: "116",
  //   instructorStudents: "936",
  //   instructorCourses: "12",
  //   position: "Professional Software Developer and Educator",
  //   aboutTeacher:
  //     "I started working as a software developer at the age of 23, and never looked back. I explored careers as varied as being a  Game Developer, Educator and Drone Pilot, over the last 25 years. None of these provided a continual challenge in the same way the combination of...",
  //   duration: "5h  30m",
  //   price: "35.00",
  //   oldPrice: "55.00",
  //   rating: "5.0",
  //   ratings: "149",
  //   topRated: true,
  //   popular: true,
  //   isNew: true,
  //   speciallyForYou: true,
  //   ongoing: false,
  //   completed: true,
  //   wishlist: true,
  //   lectures: "23",
  //   backgroundIcon: { uri: "https://via.placeholder.com/210x210" },
  //   backgroundColor: "#9BA0FC",
  //   lessons: lessons,
  // },
  // {
  //   id: "2",
  //   class: "Class 2",
  //   category: "Science",
  //   name: "Chapter 1 – Chemical Reactions and Equations.",
  //   author: "Jack Smith",
  //   thumbnail: { uri: "https://via.placeholder.com/270x270" },
  //   image: { uri: "https://via.placeholder.com/690x360" },
  //   icon: { uri: "https://via.placeholder.com/600x600" },
  //   preview_240x240: {
  //     uri: "https://via.placeholder.com/240x240",
  //   },
  //   preview_330x330: {
  //     uri: "https://via.placeholder.com/330x330",
  //   },
  //   preview_480x288: {
  //     uri: "https://via.placeholder.com/480x288",
  //   },
  //   preview_1005x495: {
  //     uri: "https://via.placeholder.com/1005x495",
  //   },
  //   location: "London Universiry",
  //   instructor: "Elizabeth Parker",
  //   instructorPhoto: { uri: "https://via.placeholder.com/273x273" },
  //   instructorRating: "4.5",
  //   instructorReviews: "116",
  //   instructorStudents: "936",
  //   instructorCourses: "12",
  //   position: "Professional Software Developer and Educator",
  //   aboutTeacher:
  //     "I started working as a software developer at the age of 23, and never looked back. I explored careers as varied as being a  Game Developer, Educator and Drone Pilot, over the last 25 years. None of these provided a continual challenge in the same way the combination of...",
  //   duration: "5h  30m",
  //   price: "35.00",
  //   oldPrice: "55.00",
  //   rating: "5.0",
  //   ratings: "149",
  //   topRated: false,
  //   popular: true,
  //   isNew: true,
  //   speciallyForYou: true,
  //   ongoing: false,
  //   completed: true,
  //   wishlist: true,
  //   lectures: "23",
  //   backgroundIcon: { uri: "https://via.placeholder.com/210x210" },
  //   backgroundColor: "#9BA0FC",
  //   lessons: lessons,
  // },
  // {
  //   id: "3",
  //   category: "Mathematics",
  //   class: "Class 1",
  //   name: "Chapter - 3: Pair of Linear Equations in Two Variables.",
  //   author: "Jack Smith",
  //   thumbnail: { uri: "https://via.placeholder.com/270x270" },
  //   image: { uri: "https://via.placeholder.com/690x360" },
  //   icon: { uri: "https://via.placeholder.com/600x600" },
  //   preview_240x240: {
  //     uri: "https://via.placeholder.com/240x240",
  //   },
  //   preview_330x330: {
  //     uri: "https://via.placeholder.com/330x330",
  //   },
  //   preview_480x288: {
  //     uri: "https://via.placeholder.com/480x288",
  //   },
  //   preview_1005x495: {
  //     uri: "https://via.placeholder.com/1005x495",
  //   },
  //   location: "London Universiry",
  //   instructor: "Elizabeth Parker",
  //   instructorPhoto: { uri: "https://via.placeholder.com/273x273" },
  //   instructorRating: "4.5",
  //   instructorReviews: "116",
  //   instructorStudents: "936",
  //   instructorCourses: "12",
  //   position: "Professional Software Developer and Educator",
  //   aboutTeacher:
  //     "I started working as a software developer at the age of 23, and never looked back. I explored careers as varied as being a  Game Developer, Educator and Drone Pilot, over the last 25 years. None of these provided a continual challenge in the same way the combination of...",
  //   duration: "5h  30m",
  //   price: "35.00",
  //   oldPrice: "55.00",
  //   oldPrice: "42.00",
  //   rating: "5.0",
  //   ratings: "149",
  //   topRated: true,
  //   popular: true,
  //   isNew: true,
  //   speciallyForYou: false,
  //   ongoing: false,
  //   completed: true,
  //   wishlist: true,
  //   lectures: "23",
  //   backgroundIcon: { uri: "https://via.placeholder.com/210x210" },
  //   backgroundColor: "#FE9BB3",
  //   lessons: lessons,
  // },
  // {
  //   id: "4",
  //   category: "English",
  //   class: "Class 1",
  //   name: "Chapter 2: Nelson Mandela Long Walk to Freedom",
  //   author: "Jack Smith",
  //   thumbnail: { uri: "https://via.placeholder.com/270x270" },
  //   image: { uri: "https://via.placeholder.com/690x360" },
  //   icon: { uri: "https://via.placeholder.com/600x600" },
  //   preview_240x240: {
  //     uri: "https://via.placeholder.com/240x240",
  //   },
  //   preview_330x330: {
  //     uri: "https://via.placeholder.com/330x330",
  //   },
  //   preview_480x288: {
  //     uri: "https://via.placeholder.com/480x288",
  //   },
  //   preview_1005x495: {
  //     uri: "https://via.placeholder.com/1005x495",
  //   },
  //   location: "London Universiry",
  //   instructor: "Elizabeth Parker",
  //   instructorPhoto: { uri: "https://via.placeholder.com/273x273" },
  //   instructorRating: "4.5",
  //   instructorReviews: "116",
  //   instructorStudents: "936",
  //   instructorCourses: "12",
  //   position: "Professional Software Developer and Educator",
  //   aboutTeacher:
  //     "I started working as a software developer at the age of 23, and never looked back. I explored careers as varied as being a  Game Developer, Educator and Drone Pilot, over the last 25 years. None of these provided a continual challenge in the same way the combination of...",
  //   duration: "5h  30m",
  //   price: "35.00",
  //   oldPrice: "55.00",
  //   rating: "5.0",
  //   ratings: "149",
  //   topRated: false,
  //   popular: true,
  //   isNew: false,
  //   speciallyForYou: true,
  //   ongoing: false,
  //   completed: true,
  //   wishlist: true,
  //   lectures: "23",
  //   backgroundIcon: { uri: "https://via.placeholder.com/210x210" },
  //   backgroundColor: "#ABC9FB",
  //   lessons: lessons,
  // },
  // {
  //   id: 1,
  //   category: "Civics",
  //   class: "Class 8",
  //   url: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd5fce0152/content/2_Class 8 Civics Why Do We Need A Parliament_  C3S1 _ WATCH ALL SESSIONS ONLY ON AAS VIDYALAYA APP.mp4",
  //   name: "Why Do We Need A Parliament",

  //   author: "XYX",
  //   thumbnail: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd5fce0152/content/2_Class 8 Civics_T.jpg",
  //   },
  //   image: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd5fce0152/content/2_Class 8 Civics_I.jpg",
  //   },
  //   icon: { uri: "https://via.placeholder.com/600x600" },
  //   preview_240x240: {
  //     uri: "https://via.placeholder.com/240x240",
  //   },
  //   preview_330x330: {
  //     uri: "https://via.placeholder.com/330x330",
  //   },
  //   preview_480x288: {
  //     uri: "https://via.placeholder.com/480x288",
  //   },
  //   preview_1005x495: {
  //     uri: "https://via.placeholder.com/1005x495",
  //   },
  //   location: "",
  //   // instructor: None,
  //   // instructorPhoto: None,
  //   // instructorRating: None,
  //   // instructorReviews: None,
  //   // instructorStudents: None,
  //   // instructorCourses: None,
  //   // position: None,
  //   // aboutTeacher: None,
  //   about: "Water: A Precious Resouce",
  //   duration: "15m 52s",
  //   // price: None,
  //   // oldPrice: None,
  //   // rating: None,
  //   // ratings: None,
  //   topRated: true,
  //   popular: true,
  //   isNew: true,
  //   // speciallyForYou: None,
  //   // ongoing: None,
  //   // completed: None,
  //   // wishlist: None,
  //   lectures: 1,
  //   // backgroundIcon: None,
  //   // backgroundColor: None,
  //   // lessons: None,
  //   description: "description",
  //   // additions: ["Develop Immersive VR Experiences.","Create Distance Grab Mechanics."],
  // },
  // {
  //   id: 2,
  //   category: "Computer",
  //   class: "Class 8",
  //   url: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd7000a87b/content/3_Class 8 ICT Understanding HTML C10S1 _ WATCH ALL SESSIONS ONLY ON AAS VIDYALAYA APP.mp4",
  //   name: "Understanding HTML",
  //   author: "XYX",
  //   thumbnail: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd7000a87b/content/3_Class 8 Computers_T.jpg",
  //   },
  //   image: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd7000a87b/content/3_Class 8 Computers_I.jpg",
  //   },
  //   icon: { uri: "https://via.placeholder.com/600x600" },
  //   preview_240x240: {
  //     uri: "https://via.placeholder.com/240x240",
  //   },
  //   preview_330x330: {
  //     uri: "https://via.placeholder.com/330x330",
  //   },
  //   preview_480x288: {
  //     uri: "https://via.placeholder.com/480x288",
  //   },
  //   preview_1005x495: {
  //     uri: "https://via.placeholder.com/1005x495",
  //   },
  //   location: "",
  //   // instructor: None,
  //   // instructorPhoto: None,
  //   // instructorRating: None,
  //   // instructorReviews: None,
  //   // instructorStudents: None,
  //   // instructorCourses: None,
  //   // position: None,
  //   // aboutTeacher: None,
  //   about: "Why Do We Need A Parliament",
  //   duration: "21m 04s",
  //   // price: None,
  //   // oldPrice: None,
  //   // rating: None,
  //   // ratings: None,
  //   topRated: true,
  //   popular: true,
  //   isNew: true,
  //   // speciallyForYou: None,
  //   // ongoing: None,
  //   // completed: None,
  //   // wishlist: None,
  //   lectures: 1,
  //   // backgroundIcon: None,
  //   // backgroundColor: None,
  //   // lessons: None,
  // },
  // {
  //   id: 3,
  //   category: "Science",
  //   class: "Class 7",
  //   url: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd909c4fec/content/1_CBSE Class 7 Science - Water _ A Precious Resource C16S1 _ WATCH ALL SESSIONS ON AAS VIDYALAYA APP.mp4",
  //   name: "Water: A Precious Resource",
  //   author: "XYX",
  //   thumbnail: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd909c4fec/content/1_Class 7 Science_T.jpg",
  //   },
  //   image: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd909c4fec/content/1_Class 7 Science_I.jpg",
  //   },
  //   icon: { uri: "https://via.placeholder.com/600x600" },
  //   preview_240x240: {
  //     uri: "https://via.placeholder.com/240x240",
  //   },
  //   preview_330x330: {
  //     uri: "https://via.placeholder.com/330x330",
  //   },
  //   preview_480x288: {
  //     uri: "https://via.placeholder.com/480x288",
  //   },
  //   preview_1005x495: {
  //     uri: "https://via.placeholder.com/1005x495",
  //   },
  //   location: "",
  //   // instructor: None,
  //   // instructorPhoto: None,
  //   // instructorRating: None,
  //   // instructorReviews: None,
  //   // instructorStudents: None,
  //   // instructorCourses: None,
  //   // position: None,
  //   // aboutTeacher: None,
  //   about: "Understanding HTML",
  //   duration: "16m 44s",
  //   // price: None,
  //   // oldPrice: None,
  //   // rating: None,
  //   // ratings: None,
  //   topRated: true,
  //   popular: true,
  //   isNew: true,
  //   // speciallyForYou: None,
  //   // ongoing: None,
  //   // completed: None,
  //   // wishlist: None,
  //   lectures: 1,
  //   // backgroundIcon: None,
  //   // backgroundColor: None,
  //   // lessons: None,
  // },
  {
    id: 1,
    category: "Civics",
    class: "Class 8",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd5fce0152/content/2_Class 8 Civics Why Do We Need A Parliament_  C3S1 _ WATCH ALL SESSIONS ONLY ON AAS VIDYALAYA APP.mp4",
    name: "Water: A Precious Resouce",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd5fce0152/content/2_Class 8 Civics_I.jpg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd5fce0152/content/2_Class 8 Civics_I.jpg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "Water: A Precious Resouce",
    duration: "15m 52s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 2,
    category: "Computer",
    class: "Class 8",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd7000a87b/content/3_Class 8 ICT Understanding HTML C10S1 _ WATCH ALL SESSIONS ONLY ON AAS VIDYALAYA APP.mp4",
    name: "Why Do We Need A Parliament",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd7000a87b/content/3_Class 8 Computers_T.jpg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd7000a87b/content/3_Class 8 Computers_I.jpg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "Why Do We Need A Parliament",
    duration: "21m 04s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 3,
    category: "Science",
    class: "Class 7",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd909c4fec/content/1_CBSE Class 7 Science - Water _ A Precious Resource C16S1 _ WATCH ALL SESSIONS ON AAS VIDYALAYA APP.mp4",
    name: "Understanding HTML",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd909c4fec/content/1_Class 7 Science_T.jpg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd909c4fec/content/1_Class 7 Science_I.jpg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "Understanding HTML",
    duration: "16m 44s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 4,
    category: "Science",
    class: "Class 10",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f3ccf48e08/content/4_विद्युतधारेचे परिणाम.mp4",
    name: "विद्युतधारेचे परिणाम",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f3ccf48e08/content/4_विद्युतधारेचे परिणाम_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f3ccf48e08/content/4_विद्युतधारेचे परिणाम_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "विद्युतधारेचे परिणाम",
    duration: "17m 36s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 5,
    category: "Science",
    class: "Class 10",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f44c0ead57/content/5_पर्यावरणीय व्यवस्थापन.mp4",
    name: "पर्यावरणीय व्यवस्थापन",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f44c0ead57/content/5_पर्यावरणीय व्यवस्थापन_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f44c0ead57/content/5_पर्यावरणीय व्यवस्थापन_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "पर्यावरणीय व्यवस्थापन",
    duration: "15m 21s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 6,
    category: "History",
    class: "Class 6",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4560557cd/content/6_वैदिक संस्कृती वैदिक वाड्मय.mp4",
    name: "वैदिक संस्कृती वैदिक वाड्मय",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4560557cd/content/6_वैदिक संस्कृती वैदिक वाड्मय_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4560557cd/content/6_वैदिक संस्कृती वैदिक वाड्मय_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "वैदिक संस्कृती वैदिक वाड्मय",
    duration: "08m 16s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 7,
    category: "Marathi",
    class: "Class 6",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f45c608411/content/7_गवतफुला रे! गवतफुला.mp4",
    name: "गवतफुला रे! गवतफुला",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f45c608411/content/7_गवतफुला रे! गवतफुला_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f45c608411/content/7_गवतफुला रे! गवतफुला_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "गवतफुला रे! गवतफुला",
    duration: "15m 42s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 8,
    category: "Marathi",
    class: "Class 7",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f468bdfbee/content/8_श्रावणमास.mp4",
    name: "श्रावणमास (कविता)",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f468bdfbee/content/8_श्रावणमास_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f468bdfbee/content/8_श्रावणमास_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "श्रावणमास (कविता)",
    duration: "16m 21s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 10,
    category: "Mathematics",
    class: "Class 6",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f46fa99794/content/10_अपूर्णांकांवरील क्रिया.mp4",
    name: "अपूर्णांकांवरील क्रिया",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f46fa99794/content/10_अपूर्णांकांवरील क्रिया_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f46fa99794/content/10_अपूर्णांकांवरील क्रिया_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "अपूर्णांकांवरील क्रिया",
    duration: "15m 14s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 11,
    category: "Mathematics",
    class: "Class 7",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47233d9ce/content/11_कोन व कोनांच्या जोड्या.mp4",
    name: "कोन व कोनांच्या जोड्या",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47233d9ce/content/11_कोन व कोनांच्या जोड्या_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47233d9ce/content/11_कोन व कोनांच्या जोड्या_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "कोन व कोनांच्या जोड्या",
    duration: "13m 30s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 12,
    category: "Mathematics",
    class: "Class 8",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4751ea60d/content/12_त्रिकोणाचे शिरोलंब व मध्यगा.mp4",
    name: "त्रिकोणाचे शिरोलंब व मध्यगा",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4751ea60d/content/12_त्रिकोणाचे शिरोलंब व मध्यगा_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4751ea60d/content/12_त्रिकोणाचे शिरोलंब व मध्यगा_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "त्रिकोणाचे शिरोलंब व मध्यगा",
    duration: "07m 47s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 13,
    category: "Mathematics",
    class: "Class 9",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f477749a31/content/13_गुणोत्तर व प्रमाण.mp4",
    name: "गुणोत्तर व प्रमाण",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f477749a31/content/13_गुणोत्तर व प्रमाण_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f477749a31/content/13_गुणोत्तर व प्रमाण_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "गुणोत्तर व प्रमाण",
    duration: "17m 46s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 14,
    category: "Mathematics",
    class: "Class 10",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47a4671f6/content/14_अर्थनियोजन.mp4",
    name: "अर्थनियोजन",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47a4671f6/content/14_अर्थनियोजन_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47a4671f6/content/14_अर्थनियोजन_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "अर्थनियोजन",
    duration: "01m 14s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
];
const courses = [
  {
    id: 1,
    category: "Science",
    class: "Class 7",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd909c4fec/content/1_CBSE Class 7 Science - Water _ A Precious Resource C16S1 _ WATCH ALL SESSIONS ON AAS VIDYALAYA APP.mp4",
    name: "Water: A Precious Resouce",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd909c4fec/content/1_Class 7 Science_T.jpg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd909c4fec/content/1_Class 7 Science_I.jpg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "Water: A Precious Resouce",
    duration: "15m 52s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: false,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 2,
    category: "Civics",
    class: "Class 8",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd5fce0152/content/2_Class 8 Civics Why Do We Need A Parliament_  C3S1 _ WATCH ALL SESSIONS ONLY ON AAS VIDYALAYA APP.mp4",
    name: "Why Do We Need A Parliament",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd5fce0152/content/2_Class 8 Civics_T.jpg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd5fce0152/content/2_Class 8 Civics_I.jpg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "Why Do We Need A Parliament",
    duration: "21m 4s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: false,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 3,
    category: "Computer",
    class: "Class 8",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd7000a87b/content/3_Class 8 ICT Understanding HTML C10S1 _ WATCH ALL SESSIONS ONLY ON AAS VIDYALAYA APP.mp4",
    name: "Understanding HTML",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd7000a87b/content/3_Class 8 Computers_T.jpg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647dd7000a87b/content/3_Class 8 Computers_I.jpg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "Understanding HTML",
    duration: "16m 44s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: false,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 4,
    category: "Science",
    class: "Class 10",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f3ccf48e08/content/4_विद्युतधारेचे परिणाम.mp4",
    name: "विद्युतधारेचे परिणाम",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f3ccf48e08/content/4_विद्युतधारेचे परिणाम_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f3ccf48e08/content/4_विद्युतधारेचे परिणाम_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "विद्युतधारेचे परिणाम",
    duration: "17m 36s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: false,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 5,
    category: "Science",
    class: "Class 10",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f44c0ead57/content/5_पर्यावरणीय व्यवस्थापन.mp4",
    name: "पर्यावरणीय व्यवस्थापन",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f44c0ead57/content/5_पर्यावरणीय व्यवस्थापन_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f44c0ead57/content/5_पर्यावरणीय व्यवस्थापन_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "पर्यावरणीय व्यवस्थापन",
    duration: "15m 21s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: false,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 6,
    category: "History",
    class: "Class 6",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4560557cd/content/6_वैदिक संस्कृती वैदिक वाड्मय.mp4",
    name: "वैदिक संस्कृती वैदिक वाड्मय - भाग १",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4560557cd/content/6_वैदिक संस्कृती वैदिक वाड्मय_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4560557cd/content/6_वैदिक संस्कृती वैदिक वाड्मय_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "वैदिक संस्कृती वैदिक वाड्मय - भाग १",
    duration: "8m 16s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: false,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 7,
    category: "Marathi",
    class: "Class 6",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f45c608411/content/7_गवतफुला रे! गवतफुला.mp4",
    name: "गवतफुला रे! गवतफुला",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f45c608411/content/7_गवतफुला रे! गवतफुला_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f45c608411/content/7_गवतफुला रे! गवतफुला_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "गवतफुला रे! गवतफुला",
    duration: "15m 42s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: false,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 8,
    category: "Marathi",
    class: "Class 7",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f468bdfbee/content/8_श्रावणमास.mp4",
    name: "श्रावणमास (कविता)",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f468bdfbee/content/8_श्रावणमास_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f468bdfbee/content/8_श्रावणमास_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "श्रावणमास (कविता)",
    duration: "16m 21s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: false,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 9,
    category: "Mathematics",
    class: "Class 6",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f46fa99794/content/10_अपूर्णांकांवरील क्रिया.mp4",
    name: "अपूर्णांकांवरील क्रिया",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f46fa99794/content/10_अपूर्णांकांवरील क्रिया_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f46fa99794/content/10_अपूर्णांकांवरील क्रिया_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "अपूर्णांकांवरील क्रिया",
    duration: "15m 14s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: false,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 10,
    category: "Mathematics",
    class: "Class 7",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47233d9ce/content/11_कोन व कोनांच्या जोड्या.mp4",
    name: "कोन व कोनांच्या जोड्या",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47233d9ce/content/11_कोन व कोनांच्या जोड्या_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47233d9ce/content/11_कोन व कोनांच्या जोड्या_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "कोन व कोनांच्या जोड्या",
    duration: "13m 30s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: false,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 11,
    category: "Mathematics",
    class: "Class 8",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4751ea60d/content/12_त्रिकोणाचे शिरोलंब व मध्यगा.mp4",
    name: "त्रिकोणाचे शिरोलंब व मध्यगा",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4751ea60d/content/12_त्रिकोणाचे शिरोलंब व मध्यगा_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f4751ea60d/content/12_त्रिकोणाचे शिरोलंब व मध्यगा_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "त्रिकोणाचे शिरोलंब व मध्यगा",
    duration: "7m 47s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 12,
    category: "Mathematics",
    class: "Class 9",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f477749a31/content/13_गुणोत्तर व प्रमाण.mp4",
    name: "गुणोत्तर व प्रमाण",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f477749a31/content/13_गुणोत्तर व प्रमाण_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f477749a31/content/13_गुणोत्तर व प्रमाण_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "गुणोत्तर व प्रमाण",
    duration: "17m 46s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 13,
    category: "Mathematics",
    class: "Class 10",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47a4671f6/content/14_अर्थनियोजन.mp4",
    name: "अर्थनियोजन",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47a4671f6/content/14_अर्थनियोजन_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/647f47a4671f6/content/14_अर्थनियोजन_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "अर्थनियोजन",
    duration: "1m 14s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 14,
    category: "English",
    class: "Class 8",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/6480395b3661b/content/15.mp4",
    name: "The best christmas present in the world",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/6480395b3661b/content/15_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/6480395b3661b/content/15_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "The best christmas present in the world",
    duration: "15m 17s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 15,
    category: "Computer",
    class: "Class 8",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/648039f82093c/content/16.mp4",
    name: "Networking Concepts",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/648039f82093c/content/16_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/648039f82093c/content/16_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "Networking Concepts",
    duration: "16m 19s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 16,
    category: "English",
    class: "Class 8",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/64803bbb3a964/content/17.mp4",
    name: "English Grammar",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64803bbb3a964/content/17_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64803bbb3a964/content/17_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "English Grammar",
    duration: "15m 46s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 17,
    category: "Hindi",
    class: "Class 7",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/64803c94c69b2/content/18.mp4",
    name: "महाभारत कथा",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64803c94c69b2/content/18_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64803c94c69b2/content/18_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "महाभारत कथा",
    duration: "10m 41s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 18,
    category: "Hindi",
    class: "Class 8",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/64803d3fc0af1/content/19.mp4",
    name: " विशेषण ",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64803d3fc0af1/content/19_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64803d3fc0af1/content/19_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: " विशेषण ",
    duration: "16m 8s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 19,
    category: "English",
    class: "Skill Development",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/64804bce20f89/content/20.mp4",
    name: "Enhance your communication skills",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804bce20f89/content/20_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804bce20f89/content/20_1.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "Enhance your communication skills",
    duration: "30m 54s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 20,
    category: "Skill",
    class: "Skill Development",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/64804cfd4dfc0/content/21.mp4",
    name: "Master the art of rearranging sentences",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804cfd4dfc0/content/21_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804cfd4dfc0/content/21_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "Master the art of rearranging sentences",
    duration: "19m 22s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  {
    id: 21,
    category: "Coding for Kids",
    class: "Skill Development",
    url: "http://192.168.30.1/frm/ui/cat/frmpackage/64804ea3444c5/content/23.mp4",
    name: "Get started with coding for kids beginners",
    author: "XYZ",
    thumbnail: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804ea3444c5/content/23_T.jpeg",
    },
    image: {
      uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804ea3444c5/content/23_I.jpeg",
    },
    icon: '{ uri: "https://via.placeholder.com/600x600" }',
    preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
    preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
    preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
    preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
    location: "",
    instructor: "",
    instructorPhoto: "",
    instructorRating: "",
    instructorReviews: "",
    instructorStudents: "",
    instructorCourses: "",
    position: "",
    aboutTeacher: "",
    about: "Get started with coding for kids beginners",
    duration: "8m 48s",
    price: "",
    oldPrice: "",
    rating: "",
    ratings: "",
    topRated: true,
    popular: true,
    isNew: true,
    speciallyForYou: "",
    ongoing: "",
    completed: "",
    wishlist: "",
    lectures: 1,
    backgroundIcon: "",
    backgroundColor: "",
    lessons: "",
  },
  // {
  //   id: 19,
  //   category: "English",
  //   class: "Skill Development",
  //   url: "http://192.168.30.1/frm/ui/cat/frmpackage/64804bce20f89/content/20.mp4",
  //   name: "Enhance your communication skills",
  //   author: "XYZ",
  //   thumbnail: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804bce20f89/content/20_T.jpeg",
  //   },
  //   image: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804bce20f89/content/20_1.jpeg",
  //   },
  //   icon: '{ uri: "https://via.placeholder.com/600x600" }',
  //   preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
  //   preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
  //   preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
  //   preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
  //   location: "",
  //   instructor: "",
  //   instructorPhoto: "",
  //   instructorRating: "",
  //   instructorReviews: "",
  //   instructorStudents: "",
  //   instructorCourses: "",
  //   position: "",
  //   aboutTeacher: "",
  //   about: "Enhance your communication skills",
  //   duration: "30m 54s",
  //   price: "",
  //   oldPrice: "",
  //   rating: "",
  //   ratings: "",
  //   topRated: true,
  //   popular: false,
  //   isNew: true,
  //   speciallyForYou: "",
  //   ongoing: "",
  //   completed: "",
  //   wishlist: "",
  //   lectures: 1,
  //   backgroundIcon: "",
  //   backgroundColor: "",
  //   lessons: "",
  // },
  // {
  //   id: 20,
  //   category: "Skill",
  //   class: "Skill Development",
  //   url: "http://192.168.30.1/frm/ui/cat/frmpackage/64804cfd4dfc0/content/21.mp4",
  //   name: "Master the art of rearranging sentences",
  //   author: "XYZ",
  //   thumbnail: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804cfd4dfc0/content/21_T.jpeg",
  //   },
  //   image: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804cfd4dfc0/content/21_I.jpeg",
  //   },
  //   icon: '{ uri: "https://via.placeholder.com/600x600" }',
  //   preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
  //   preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
  //   preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
  //   preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
  //   location: "",
  //   instructor: "",
  //   instructorPhoto: "",
  //   instructorRating: "",
  //   instructorReviews: "",
  //   instructorStudents: "",
  //   instructorCourses: "",
  //   position: "",
  //   aboutTeacher: "",
  //   about: "Master the art of rearranging sentences",
  //   duration: "19m 22s",
  //   price: "",
  //   oldPrice: "",
  //   rating: "",
  //   ratings: "",
  //   topRated: true,
  //   popular: false,
  //   isNew: true,
  //   speciallyForYou: "",
  //   ongoing: "",
  //   completed: "",
  //   wishlist: "",
  //   lectures: 1,
  //   backgroundIcon: "",
  //   backgroundColor: "",
  //   lessons: "",
  // },
  // {
  //   id: 21,
  //   category: "Coding for Kids",
  //   class: "Skill Development",
  //   url: "http://192.168.30.1/frm/ui/cat/frmpackage/64804ea3444c5/content/23.mp4",
  //   name: "Get started with coding for kids beginners",
  //   author: "XYZ",
  //   thumbnail: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804ea3444c5/content/23_T.jpeg",
  //   },
  //   image: {
  //     uri: "http://192.168.30.1/frm/ui/cat/frmpackage/64804ea3444c5/content/23_I.jpeg",
  //   },
  //   icon: '{ uri: "https://via.placeholder.com/600x600" }',
  //   preview_240x240: '{uri: "https://via.placeholder.com/240x240",}',
  //   preview_330x330: '{uri:"https://via.placeholder.com/330x330",}',
  //   preview_480x288: '{uri:"https://via.placeholder.com/480x288",}',
  //   preview_1005x495: '{uri:"https://via.placeholder.com/1005x495",}',
  //   location: "",
  //   instructor: "",
  //   instructorPhoto: "",
  //   instructorRating: "",
  //   instructorReviews: "",
  //   instructorStudents: "",
  //   instructorCourses: "",
  //   position: "",
  //   aboutTeacher: "",
  //   about: "Get started with coding for kids beginners",
  //   duration: "8m 48s",
  //   price: "",
  //   oldPrice: "",
  //   rating: "",
  //   ratings: "",
  //   topRated: true,
  //   popular: false,
  //   isNew: true,
  //   speciallyForYou: "",
  //   ongoing: "",
  //   completed: "",
  //   wishlist: "",
  //   lectures: 1,
  //   backgroundIcon: "",
  //   backgroundColor: "",
  //   lessons: "",
  // },
];

export { courses, courses1 };

const data = {
  Files: [
    {
      Description: "",
      FileType: "Video",
      Filename:
        "1_CBSE Class 7 Science - Water _ A Precious Resource C16S1 _ WATCH ALL SESSIONS ON AAS VIDYALAYA APP.mp4",
      Tag: "Movie",
      URL: "ui/cat/frmpackage/647dd909c4fec/content/1_CBSE Class 7 Science - Water _ A Precious Resource C16S1 _ WATCH ALL SESSIONS ON AAS VIDYALAYA APP.mp4",
    },
    {
      Description: "",
      FileType: "Image",
      Filename: "1_Class 7 Science_I.jpg",
      Tag: "Background",
      URL: "ui/cat/frmpackage/647dd909c4fec/content/1_Class 7 Science_I.jpg",
    },
    {
      Description: "",
      FileType: "Image",
      Filename: "1_Class 7 Science_T.jpg",
      Tag: "Thumbnail",
      URL: "ui/cat/frmpackage/647dd909c4fec/content/1_Class 7 Science_T.jpg",
    },
  ],
  Meta: { Type: "FrmPackage" },
  Package: {
    Description:
      "AAS Vidyalaya offers enriching and comprehensive educational content tailored specifically for Class 6 to 10 students, providing them with a well-rounded learning experience to enhance their knowledge and academic growth",
    Name: "Class 07-Science",
    PackageType: "PVOD",
    Uuid: "647dd909c4fec",
  },
};
const res = [
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Why Do We Need A Parliament",
      Name: "Class 08 -Civics",
      PackageType: "PVOD",
      Uuid: "647dd5fce0152",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description:
        "AAS Vidyalaya offers enriching and comprehensive educational content tailored specifically for Class 6 to 10 students, providing them with a well-rounded learning experience to enhance their knowledge and academic growth",
      Name: "Class 08- Computer",
      PackageType: "PVOD",
      Uuid: "647dd7000a87b",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description:
        "AAS Vidyalaya offers enriching and comprehensive educational content tailored specifically for Class 6 to 10 students, providing them with a well-rounded learning experience to enhance their knowledge and academic growth",
      Name: "Class 07-Science",
      PackageType: "PVOD",
      Uuid: "647dd909c4fec",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 10-Science-विद्युतधारेचे परिणाम",
      Name: "Class 10-Science-विद्युतधारेचे परिणाम",
      PackageType: "PVOD",
      Uuid: "647f3ccf48e08",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 10-Science-पर्यावरणीय व्यवस्थापन",
      Name: "Class 10-Science-पर्यावरणीय व्यवस्थापन",
      PackageType: "PVOD",
      Uuid: "647f44c0ead57",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 06-History-वैदिक संस्कृती वैदिक वाड्मय - भाग १",
      Name: "Class 06-History-वैदिक संस्कृती वैदिक वाड्मय",
      PackageType: "PVOD",
      Uuid: "647f4560557cd",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 06-Marathi-गवतफुला रे! गवतफुला",
      Name: "Class 06-Marathi-गवतफुला रे! गवतफुला",
      PackageType: "PVOD",
      Uuid: "647f45c608411",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 07-Marathi-श्रावणमास (कविता)",
      Name: "Class 07-Marathi-श्रावणमास (कविता)",
      PackageType: "PVOD",
      Uuid: "647f468bdfbee",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 06-MATHS-अपूर्णांकांवरील क्रिया",
      Name: "Class 06-MATHS-अपूर्णांकांवरील क्रिया",
      PackageType: "PVOD",
      Uuid: "647f46fa99794",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 07-MATHS-कोन व कोनांच्या जोड्या",
      Name: "Class 07-MATHS-कोन व कोनांच्या जोड्या",
      PackageType: "PVOD",
      Uuid: "647f47233d9ce",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 08-MATHS-त्रिकोणाचे शिरोलंब व मध्यगा",
      Name: "Class 08-MATHS-त्रिकोणाचे शिरोलंब व मध्यगा",
      PackageType: "PVOD",
      Uuid: "647f4751ea60d",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 09-MATHS-गुणोत्तर व प्रमाण",
      Name: "Class 09-MATHS-गुणोत्तर व प्रमाण",
      PackageType: "PVOD",
      Uuid: "647f477749a31",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 10-MATHS-अर्थनियोजन",
      Name: "Class 10-MATHS-अर्थनियोजन",
      PackageType: "PVOD",
      Uuid: "647f47a4671f6",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 8-English-The best christmas present in the world",
      Name: "Class 8-English-The best christmas present in the world",
      PackageType: "PVOD",
      Uuid: "6480395b3661b",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 8-Computer-Networking Concepts",
      Name: "Class 8-Computer-Networking Concepts",
      PackageType: "PVOD",
      Uuid: "648039f82093c",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 8-English-English Grammar",
      Name: "Class 8-English-English Grammar",
      PackageType: "PVOD",
      Uuid: "64803bbb3a964",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 7-Hindi-महाभारत कथा",
      Name: "Class 7-Hindi-महाभारत कथा",
      PackageType: "PVOD",
      Uuid: "64803c94c69b2",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description: "Class 8-Hindi- विशेषण ",
      Name: "Class 8-Hindi- विशेषण ",
      PackageType: "PVOD",
      Uuid: "64803d3fc0af1",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description:
        "Skill Development-English-Enhance your communication skills",
      Name: "Skill Development-English-Enhance your communication skills",
      PackageType: "PVOD",
      Uuid: "64804bce20f89",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description:
        "Skill Development-English-Master the art of rearranging sentences",
      Name: "Skill Development-English-Master the art of rearranging sentences",
      PackageType: "PVOD",
      Uuid: "64804cfd4dfc0",
    },
  },
  {
    Files: [[Object], [Object], [Object]],
    Meta: { Type: "FrmPackage" },
    Package: {
      Description:
        "Skill Development-Coding for Kids-Get started with coding for kids beginners",
      Name: "Skill Development-Coding for Kids-Get started with coding for kids beginners",
      PackageType: "PVOD",
      Uuid: "64804ea3444c5",
    },
  },
];
